#!/usr/bin/env python3
"""Check for word breaking issues in PDF Quick Fixes"""

try:
    from PyPDF2 import PdfReader
    import re
    
    with open('seo_audit_report.pdf', 'rb') as f:
        reader = PdfReader(f)
        text = ''
        for page in reader.pages:
            text += page.extract_text()
        
        # Find Quick Fixes section
        if 'QUICK FIXES' in text:
            idx = text.find('QUICK FIXES')
            end_idx = text.find('Generated by Mr Moosa', idx)
            section = text[idx:end_idx] if end_idx > 0 else text[idx:idx+2500]
            
            print('=' * 80)
            print('QUICK FIXES SECTION (RAW):')
            print('=' * 80)
            print(repr(section))  # Show with escape sequences to see spaces clearly
            print('\n' + '=' * 80)
            print('QUICK FIXES SECTION (FORMATTED):')
            print('=' * 80)
            print(section)
            
            # Check for word breaking patterns: letter + space + letter
            broken_words = re.findall(r'\b([a-z]) ([a-z])\b', section, re.IGNORECASE)
            
            if broken_words:
                print(f'\n❌ WORD BREAKING DETECTED: {len(broken_words)} instances')
                print('Examples:', broken_words[:5])
            else:
                print('\n✅ NO word breaking detected!')
                
            # Check specific problematic words
            problem_words = ['descri ption', 'exam ple', 'p age', 'l ocation', 'scri pt', 'meta description']
            found_issues = [w for w in problem_words if w.lower() in section.lower()]
            
            if found_issues:
                print(f'\n❌ FOUND BROKEN WORDS: {found_issues}')
            else:
                print('✅ No specific broken words found')
                
except Exception as e:
    print(f'Error: {e}')
    import traceback
    traceback.print_exc()
